version: '3.9'

services:
  web:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "8087:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/usr/share/nginx/html:ro
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

