# Generated by Django 5.1.2 on 2024-10-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_registro", models.DateTimeField()),
                ("nivel", models.CharField(max_length=1)),
            ],
        ),
    ]
